name: Newman Test Run
on:
  push:
    branches:
    - master
    - staging
jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          collection: RemoteBikeTesting.postman_collection.json
      - run: npm install -g newman
      - run: newman run https://github.com/matthewdheilmanvanderbilt/Final-Project/.github/workflows/RemoteBikeTesting.postman_collection.json
